name: build

on:
  # push:
  # pull_request:

  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
    - uses: actions/checkout@v2

    - name: Build iso
      run: |
        bash build.sh

    - name: Env
      run: |
        echo "${{ env.BUILD_TAG }}"
        echo "${{ env.image_name }}"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.BUILD_TAG }}
        path: /out/*

    - name: Create release
      # if: ${{ github.event_name == 'schedule' }}
      uses: softprops/action-gh-release@v1
      with:
        files: /out/*
        tag_name: ${{ env.BUILD_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
